language: android
dist: trusty
android:
  components:
    - build-tools-30.0.2
    - android-30

before_install:
  - yes | sdkmanager --licenses

script:
  - cd UltimatePlaylist
  - ./gradlew build