language: android
dist: trusty
android:
  components:
    - build-tools-30.0.2
    - android-30

before_install:
  - echo yes | sdkmanager "build-tools;30.0.2"
  - echo yes | sdkmanager "android:30"

script:
  - cd UltimatePlaylist
  - ./gradlew build