version: '3'

services:
  multimusicstreaming_devenvironment:
    build:
      context: .
      dockerfile: ./Dockerfile
    container_name: MultiMusicStreamingDevelopmentContainer
    ports:
      - 5901:5901
    volumes:
      - ../app:/app:rw
      - ../sdk:/sdk:rw
      - ./vncrc:/root/.vncrc:ro
